//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarStoreEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarRecord
    {
        public int Id { get; set; }
        public string Model { get; set; }
        public string Company { get; set; }
        public string Price { get; set; }
        public string Features { get; set; }
    }
}
