//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarStoreEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarStoreEntities : DbContext
    {
        public CarStoreEntities()
            : base("name=CarStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarRecord> CarRecords { get; set; }
        public virtual DbSet<ContactRecord> ContactRecords { get; set; }
        public virtual DbSet<SaleRecord> SaleRecords { get; set; }
        public virtual DbSet<StaffRecord> StaffRecords { get; set; }
    }
}
